### ISSUE TITLE
trying to build this with gcc-7.1 built from source

### ISSUE THREAD

**Issue by ymolists** [phiste/flappy_koala#1]
I left c++ a long time ago specifically for these unfortunate build errors. My hair is almost gray from all that but i cant stop doing it :))) 

cmake version 3.8 does not recognise set(CMAKE_CXX_STANDARD 17) so you might want to add that to the readme 

Here is what i used to build the actual engine with no errors for cmake
```
tools:
$cmake --version
cmake version 3.9.1
CMake suite maintained and supported by Kitware (kitware.com/cmake).

$gcc-7.1 --version
gcc-7.1 (GCC) 7.1.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



  cmake .. \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_VERBOSE_MAKEFILE=ON \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_C_COMPILER=gcc-7.1 \
      -DCMAKE_CXX_COMPILER=g++-7.1
```

I also used the same cmake flags as ^^^ to build this project [flappy_koala]  but got this error:

```

[ 68%] Building CXX object CMakeFiles/flappy_koala.dir/src/main.cpp.o
/home/ymo/3rdp/apps/gcc/gcc-7.1.0.dist/bin/g++-7.1    -I/data/3rdp/games/kengine/flappy_koala/src -I/data/3rdp/games/kengine/flappy_koala/kengine/. -I/data/3rdp/games/kengine/flappy_koala/kengine/putils/mediator/. -I/data/3rdp/games/kengine/flappy_koala/kengine/putils/. -I/data/3rdp/games/kengine/flappy_koala/kengine/putils/pluginManager/. -I/data/3rdp/games/kengine/flappy_koala/common -I/usr/include/lua5.2 -I/data/3rdp/games/kengine/flappy_koala/kengine/putils/lua/. -I/data/3rdp/games/kengine/flappy_koala/kengine/putils/pse -I/data/3rdp/games/kengine/flappy_koala/kengine/putils/pse/SFML/include  -std=c++17   -o CMakeFiles/flappy_koala.dir/src/main.cpp.o -c /data/3rdp/games/kengine/flappy_koala/src/main.cpp
In file included from /data/3rdp/games/kengine/flappy_koala/src/main.cpp:3:0:
/data/3rdp/games/kengine/flappy_koala/kengine/./EntityManager.hpp: In member function ‘void kengine::EntityManager::registerTypes()’:
/data/3rdp/games/kengine/flappy_koala/kengine/./EntityManager.hpp:129:42: error: expected primary-expression before ‘...’ token
                     s.registerTypes<Types...>();
                                          ^~~
/data/3rdp/games/kengine/flappy_koala/kengine/./EntityManager.hpp:129:42: error: expected ‘;’ before ‘...’ token
In file included from /data/3rdp/apps/gcc/gcc-7.1.0.dist/include/c++/7.1.0/cassert:44:0,
                 from /data/3rdp/games/kengine/flappy_koala/kengine/putils/./lua/sol.hpp:2192,
                 from /data/3rdp/games/kengine/flappy_koala/kengine/putils/./lua/lua.hpp:3,
                 from /data/3rdp/games/kengine/flappy_koala/kengine/./common/systems/LuaSystem.hpp:5,
                 from /data/3rdp/games/kengine/flappy_koala/src/main.cpp:5:
/data/3rdp/games/kengine/flappy_koala/kengine/putils/./lua/sol.hpp: In instantiation of ‘T* sol::optional<T>::operator->() [with T = sol::basic_object<sol::reference>]’:
/data/3rdp/games/kengine/flappy_koala/kengine/putils/./lua/sol.hpp:14376:37:   required from here
/data/3rdp/games/kengine/flappy_koala/kengine/putils/./lua/sol.hpp:2747:4: error: ‘__assert_fail’ was not declared in this scope
    assert(initialized());
 ```

**Comment by phiste** [comment]
This is strange, I get no errors on Archlinux with gcc 7.1.1. Looking at those errors I don't see what I'm doing wrong, the syntax seems legal.

I'll try with clang and keep you posted :)

**Comment by ymolists** [comment]
Here are the flags i used to build gcc
```
$g++-7.1 -v
Using built-in specs.
COLLECT_GCC=g++-7.1
COLLECT_LTO_WRAPPER=/data/3rdp/apps/gcc/gcc-7.1.0.dist/bin/../libexec/gcc/x86_64-pc-linux-gnu/7.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../gcc-7.1.0/configure --prefix=/home/ymo/3rdp/apps/gcc/gcc-7.1.0.dist --enable-languages=c,c++ --disable-multilib --program-suffix=-7.1
Thread model: posix
gcc version 7.1.0 (GCC)
ymo@ymodt:/data/3rdp/games/kengine/kengine-latest/build$
```

**Comment by phiste** [comment]
Ok, gcc finally finished compiling (4 hours, wow)

It seems the error occurs in gcc 7.1.0 but not in 7.1.1. So one easy fix (and probably the best thing to do) is switch to that version :)

I'm going to toy a bit with the code to try and get it to compile on 7.1.0 and will close this issue once it's fixed

**Comment by phiste** [comment]
Fixed. The error had to do with gcc's detection of template members in deduced types, changing

```cpp
s.registerTypes<Types...>();
```

to

```cpp
s.template registerTypes<Types...>();
```

did it :)

**Comment by ymolists** [comment]
Should we file a bug against gcc ? maybe this is already in their list ?

**Comment by phiste** [comment]
If it works in 7.1.1 I'm hoping it does in 7.2 as well (although you never know...). 7.2 hasn't rolled out to Archlinux officially so I haven't tried it yet, but feel free to!

The bug has already been fixed in the latest versions, so no need to file a bug report
